#!/bin/bash

set -o errexit
set -o nounset

configfile="${1:-config}"
test -r ${configfile} || touch ${configfile}

function readConfig() {
    local varName=$1
    local defaultValue=${2:-""}
    local fileValue=$(cat ${configfile} | grep ^"export ${varName}" | cut -d"=" -f2 | tr -d '"')
    local suggestedValue="${fileValue:-${defaultValue}}"
    local readValue
    read -p "${varName}[${suggestedValue}]: " readValue
    echo "${readValue:-$suggestedValue}"
}

# azure credentials
arm_subscription_id=$(readConfig "ARM_SUBSCRIPTION_ID")
arm_client_id=$(readConfig "ARM_CLIENT_ID")
arm_client_secret=$(readConfig "ARM_CLIENT_SECRET")
arm_tenant_id=$(readConfig "ARM_TENANT_ID")

# kcd informations
kcd_vnet_resource_group_name=$(readConfig "KCD_VNET_RESOURCE_GROUP_NAME")
kcd_vnet_name=$(readConfig "KCD_VNET_NAME")
kcd_name=$(readConfig "KCD_NAME")
kcd_image_version=$(readConfig "KCD_IMAGE_VERSION")
kcd_location=$(readConfig "KCD_LOCATION")
kcd_subnet_id=$(readConfig "KCD_SUBNET_ID")
kcd_ssh_pub_key_file=$(readConfig "KCD_SSH_PUB_KEY_FILE")
kcd_zookeeper_quorum=$(readConfig "KCD_ZOOKEEPER_QUORUM")


cat << VARS > ${configfile}
#################
# readed values #
#################
# azure informations
export ARM_SUBSCRIPTION_ID="${arm_subscription_id}"
export ARM_CLIENT_ID="${arm_client_id}"
export ARM_CLIENT_SECRET="${arm_client_secret}"
export ARM_TENANT_ID="${arm_tenant_id}"
# kcd informations
export KCD_VNET_RESOURCE_GROUP_NAME="${kcd_vnet_resource_group_name}"
export KCD_VNET_NAME="${kcd_vnet_name}"
export KCD_NAME="${kcd_name}"
export KCD_IMAGE_VERSION="${kcd_image_version}"
export KCD_LOCATION="${kcd_location}"
export KCD_SUBNET_ID="${kcd_subnet_id}"
export KCD_SSH_PUB_KEY_FILE="${kcd_ssh_pub_key_file}"
export KCD_ZOOKEEPER_QUORUM="${kcd_zookeeper_quorum}"

###################
# computed values #
###################
# packar variables
export PACKER_IMAGE_RESOURCE_GROUP="${kcd_name}"
export PACKER_IMAGE_LOCATION="${kcd_location}"
export PACKER_IMAGE_NAME="${kcd_name}-${kcd_image_version}"
# terraform variables
export TF_VAR_name="${kcd_name}"
export TF_VAR_vnet_name="${kcd_vnet_name}"
export TF_VAR_vnet_resource_group_name="${kcd_vnet_resource_group_name}"
export TF_VAR_subnet_id="${kcd_subnet_id}"
export TF_VAR_image_name="${kcd_name}-${kcd_image_version}"
export TF_VAR_ssh_pub_key_file="${kcd_ssh_pub_key_file}"
export TF_VAR_zookeeper_quorum="${kcd_zookeeper_quorum}"
VARS
